# Generated by Django 5.1.3 on 2024-11-08 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regisztracio', '0002_alter_csapatregisztracio_felhasznalonev_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csapatregisztracio',
            name='felhasznalonev',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='csapatregisztracio',
            name='jelszo',
            field=models.CharField(max_length=50),
        ),
    ]
