# Generated by Django 5.1.3 on 2024-11-08 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regisztracio', '0003_alter_csapatregisztracio_felhasznalonev_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('team_name', models.CharField(max_length=100)),
                ('school_name', models.CharField(max_length=100)),
                ('teacher_name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=20)),
                ('programming_language', models.CharField(max_length=20)),
                ('registration_deadline', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='CsapatRegisztracio',
        ),
    ]
