# Generated by Django 5.1.3 on 2024-11-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regisztracio', '0004_userdata_delete_csapatregisztracio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='registration_deadline',
        ),
        migrations.AddField(
            model_name='userdata',
            name='member1_grade',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='member1_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='member2_grade',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='member2_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='member3_grade',
            field=models.CharField(default='N/A', max_length=10),
        ),
        migrations.AddField(
            model_name='userdata',
            name='member3_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='userdata',
            name='substitute_grade',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='substitute_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
